---
title: "RStudioとGitでバージョン管理"
author: "Shouhei TAKEUCHI"
date: \today
header-includes:
   - \usepackage{zxjatype} # 日本語組版パッケージ
   - \setmainfont{Meiryo} # 英語のメインフォント
   - \setjamainfont{Meiryo} # 日本語のメインフォント
   - \setmonofont{Yutapon coding Regular} # Rスクリプト部分のフォント
output:
  pdf_document:
    latex_engine: xelatex # zxjatypeパッケージを使用するために変更
    toc: true
    toc_depth: 2 # 見出しの表示とその深さを指定
fontsize: 12pt
---
\newpage

# このドキュメントの目的

Windows環境で、RStudioとGitを使って、Rのコードのバージョン管理（変更履歴を残す）および共有ができるようになることを目的とする。
\footnote{Macは手元にないので、試せない。}
また、RStudioとGitの連携において、テキストファイル以外を使うためには、工夫が必要なので、そちらについても軽く触れておく。
\footnote{この資料では、RとRStudioのインストールが終わっていることを前提とする。}


## 最終更新時の情報

* このファイルの最終更新日時：`r Sys.time()`
* Rのバージョン：3.2.4 Revised
* RStudioのバージョン：00.99.893
* Gitのバージョン：2.7.1


# Gitとは？

コードを書いたファイル（テキストファイル）をバージョン管理する際に、変更のたびにファイル名を変えて履歴を管理すると、ファイル数がふくれあがっていく。
Gitは、そういう問題を解決するために、ファイルの「変更履歴を記録」しておくための仕組みとなる。

サルでもわかるGit入門\footnote{http://www.backlog.jp/git-guide/}の入門編までを読んでみると使い方の簡単な説明があり、すごく理解の助けになる。
最終的には、発展編のbranchまで理解しておきたい。


# Git関連用語

Gitを扱う上で、理解しておくべき言葉のまとめを先にしておく。

* レポジトリ：ファイルやフォルダの状態を記録する場所
* ローカルレポジトリ：自分の手元のPC上にあるレポジトリ
* リモートレポジトリ：Github\footnote{https://github.com/}やBitbucket\footnote{https://bitbucket.org/}などのサーバ上にあるレポジトリ
* コミット（commit）：ファイルやフォルダの追加・変更を記録する操作
* プッシュ（push）：ローカルレポジトリの変更履歴をアップロードすること
* プル（pull）：リモートレポジトリから最新の変更履歴をダウンロードし、ローカルレポジトリに取り込むこと
* クローン（clone）：リモートレポジトリをローカルに複製すること
* ブランチ（branch）：履歴の流れを分岐して記録するもの\footnote{RStudioとGitの連携では、最後にすべてマージすることが多くなると思う。}
* マージ（merge）：異なるブランチの変更を統合すること


# Gitのインストール

Git本家\footnote{https://git-scm.com/}から最新版（Git-2.8.2-64-bit.exe：64bitシステムの場合）をダウンロードし、インストールする。
オプションはよく読んで設定する。
<!-- 以下にいくつかの設定例を示しているが、オプションは、インストールするバージョンによって順番が変わったりするので、一度全てに目を通してからインストールを開始すると良い。 -->
<!-- よくわからない場合は、すべてデフォルトでも良いと思うが、インストールの際に共有相手と相談すること。 -->


<!-- ## Select Component -->

<!-- * Additional icon: クイックランチやデスクトップのショートカットアイコンは邪魔なので、すべてOffにする。 -->
<!-- * Use a True Type font～: Onにすると文字化けするらしい。 -->
<!-- * 他はそのままでNext -->


<!-- ## Select Start Menu Folder -->

<!-- とくに変更する必要はないのでそのままにする。 -->


<!-- ## Adjusting your PATH environment -->

<!-- PATHの設定。わからなければ、「Run Git from the Windows Command Prompt」を選択する。 -->

<!-- * Use Git Bash only: PATHを設定しない。Git BashからのみGitコマンドが使用可能 -->
<!-- * Run Git from the Windows Command Prompt: git/gitkコマンドだけPATHに設定 -->
<!-- * Run Git and includeed Unix tools from the Windows Command Prompt：git/gitkとmsysのコマンドもPATHに設定 -->


<!-- ## Configuring the line ending conversions -->

<!-- 改行コードの設定に関する項目だが、後で変更可能なので、わからなければそのままでかまわない。\footnote{http://d.hatena.ne.jp/xyk/20130920/1379659991} -->


<!-- ## Configuring the terminal emulator to use with Git Bash -->

<!-- そのままでかまわない。 -->

<!-- * Use MinTTY (the default terminal of MSys2) -->
<!-- * Use Windows' default console window -->


<!-- ## Configuring experimental performance tweaks -->

<!-- わからないので、そのままOff。 -->


# Gitのセットアップ

残念ながら、Gitはインストールしてすぐ簡単に使えるものではない。
最低限必要な設定などを以下にまとめておく。


## Gitの設定

最低限やることは以下の通り。

1. Windowsの「すべてのプログラム」->「Git」->「Git Bash」より、以下のコマンドを用いてGitに作業者の情報を登録する。

> git config \--global user.email “GitやGitHub、Bitbucketで使うメールアドレス”  
> git config \--global user.name “Gitで使う名前”

当然、メールアドレスと、名前は自分のものに変更する。
名前は、半角英数のみに限定しておいた方が、余計なトラブルを起こさない。
\footnote{個人的には、トラブルは可能な限り避けたいので、ニックネームを使って名前にもスペースを入れないようにしている。}

ここの設定を怠ると、誰がコードに変更を加えたのかがわからなくなるので、十分に注意して設定する。
特にGitHubやBitbucketなどリモート環境での共有・管理を考えている場合は、メールアドレスと名前を統一しておくとよい。
また、下記のコマンドで設定の確認ができるので、試しておくと良い。

> git config \--list


## RStudioでGitを有効にする

RStudio側でもGitを有効にする必要がある。
\footnote{勝手に選んでくれている時もあるが、一応確認しておく。}

1. RStudioで、「Tools」->「Global Options...」->「Git/SVN」を選択
2. Enable version control interface for RStudio projectsにチェックを入れる。
3. Git executable:に「C:/Program Files/Git/bin/git.exe」を追加（Browse...からgit.exeを探せば良い）


## プロジェクトでGitを有効にする

RStudioでGitを有効にしても、勝手に全てのプロジェクトでGitが有効になるわけではない。
プロジェクトごとにGitを有効にする必要がある。
\footnote{もちろん、有効にしなくても普通にRStudioは使える。}


### Gitが有効な新規プロジェクトの作成

RStudioとGitの連携では、基本的にリモートレポジトリを使うことが想定されている。
なので、事前にGitHubかBitbucketにレポジトリを作成しておくとよい。

1. 「New project」->「Version Control」->「Git」を選択
2. 「Repository URL:」にリモートレポジトリのURLを貼り付ける。
\footnote{例: https://github.com/takeshou/rstudiogit.git}
問題がなければ、自動で、「Project directory name:」も入力される。
3. 「Create project as subdirectory of:」に、プロジェクトのフォルダを作成するフォルダを指定する。
\footnote{Macだと自動では入らない上、うまく行かない場合もある。
この件については、手元にMacがないので、調べられないが、どうにかしたいので、知っている人はコメントなどで教えていただけると助かります。}


### 既存のプロジェクトでGitを有効にする

1. 「Tools」->「Project Options...」->「Git/SVN」を選択
2. 「Version control system:」で「Git」を選択

この場合、リモートの指定は、GitタブのMoreから、Shellを開いて、以下のように行う。

> git remote add origin "リモートレポジトリのURL"

この作業は、最初は複雑に思えるので、できる限り、新規にプロジェクトを作るように考えるとよい。


# Gitでの管理

実際にコードをバージョン管理する方法に移る。
基本的な手順は、新しくプロジェクトを立ち上げるときと既存のプロジェクトに参加する場合で異なる。


## 新しくプロジェクトを立ち上げるとき

1. リモートにレポジトリを作成
2. レポジトリをクローン
3. ファイルの作成・管理開始


## 既存のプロジェクトに参加するとき

1. レポジトリのクローン
2. ファイルの変更・作成・管理開始


## コミット

1. Gitでバージョン管理するプロジェクトで、ファイルを作成（いつも通り）する。
2. ある程度意味をもったまとまりを変更したら、Gitタブで、チェックボックスをクリックして選択し（最初の1回は、アイコンがA（Add）、それ以降はM（Modified）に変わる。）、Commitをクリックする。
3. 「Review Changesウィンドウ」が立ち上がるので、右上の「Commit message」に変更についてコメントをして、チェックが付いていることを確認して「Commit」ボタンを押す。

コメントは、「1行目：概要」、「2行目：空行」、「3行目：詳細な記述」が推奨されている。
RStudioでのみGitを使っていると、2行目以降のコメントは読めないが、GitHubなどリモートにPushするとリモート側では見ることが出来る。


## バージョンを戻す方法

コミット前に以前の状態に戻すのであれば、Gitウィンドウでファイルを選択し、Revertボタンを押せば良い。

すでにコミットした状態であれば、下記のような手順を踏む。

1. 「Review Changesウィンドウ」左上にある「History」でコードの履歴を参照する。
2. 戻したいバージョンを選択し、右の中頃にあるView fileをクリック。
3. 名前を付けて保存でも、上書き保存でもする。


### 管理したくないファイルをコミットしてしまった場合

RStudioではGitのすべての機能がクリックで使えるわけではない。
いくつかの作業は、「Gitタブ」->「More」->「Shell」を使うか、Git Bashを使ってGitの作法に従って行うか、バッドノウハウ的に行う必要がある。
たとえば、Gitで管理したくないファイルをコミットしてしまった場合は、以下の2通りが考えられる。

1. git commit --amendを使う。
2. 先に別フォルダにコピーしておいて、RStudioのFilesタブで選択して、Deleteボタンを使う。

Gitの作法に従うのは、正しい方法を知っていれば、何の問題もない。
2つめのバッドノウハウ的な作法は、注意が必要となる。
RStudioのFileタブにあるDeleteは、Gitの管理からも削除するようになっているが、Windowsのフォルダから、普通のファイルのように削除した場合、Gitの管理の記録は残ったままになる。
結果的に、Gitには管理すべきファイルとして記録されたまま、ファイルが存在しないという状態になってしまい、厄介になことが起こってしまう。


## リモートで管理する

共有・共同開発・バックアップなどいろんな用途があるが、リモートで管理する場合は、先にGitHubやBitbucketの登録が必要となる。
登録にはメールアドレスが必要だが、大学のアドレスを使うと、Bitbucketはアカデミックライセンスとなって便利だし、GitHubは大学のアドレスを登録した後、申請すればアカデミックライセンスになってプライベートレポジトリ（非公開）が使えるようになる。
申請が面倒な場合は、Bitbucketだと最初からプライベートレポジトリが使えるので、そちらを登録すると良い。
ただし、GitHubの方が標準的なものとして扱われており、情報も充実しているので、注意すること。

<!-- リモートの登録
git remote系も書く。 -->



<!-- http://qiita.com/rild/items/46ec3b2e4a99bd5cc3b0 -->
